[package]
name = "posh"
version = "0.1.0"
edition = "2021"

[dependencies]
glsl = "6.0"
version = "1.1.0"
static_assertions = "1.1.0"

posh-macros = { path = "macros", version = "*" }

[dev-dependencies]
posh = { version = "*", path = "." }

[dependencies.uuid]
version = "1.1.0"
features = ["v4"]

[workspace]
members = ["macros"]