[package]
name = "posh"
version = "0.1.0"
edition = "2021"

[dependencies]
glsl = "6.0"
version = "1.1.0"
static_assertions = "1.1.0"
sealed = "0.4"

nalgebra = { version = "0.31", optional = true }

posh-macros = { path = "macros", version = "*" }

[dev-dependencies]
posh = { version = "*", path = ".", features = ["nalgebra"] }

[workspace]
members = ["macros", "glace"]