[package]
name = "fsl"
version = "0.1.0"
edition = "2021"

[features]
macros = ["fsl-macros"]

[dependencies]
glsl = "6.0"
version = "1.1.0"
fsl-macros = { path = "macros", version = "*", optional = true }

[dev-dependencies]
fsl = { version = "*", features = ["macros"], path = "." }

[dependencies.uuid]
version = "1.1.0"
features = ["v4"]

[workspace]
members = ["macros"]